- hosts: all
  tags: always
  become: true
  gather_facts: true
  pre-tasks:
    - name: pre-run | Update apt cache
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_distribution in ['Debian', 'Ubuntu']

# roles
