# Initialize client machine with Ansible
- hosts: all
  gather_facts: true

  roles:
    - role: bootstrap
      tags: bootstrap

    - role: base
      tags: base

- hosts: wireguard
  gather_facts: true
  become: true

  roles:
    - role: wireguard
      tags: wireguard_keys
      wireguard_phase: keys

    - role: wireguard
      tags: wireguard
      wireguard_phase: config

- hosts: infomaniak
  gather_facts: true
  become: true

  roles:
    - role: docker
      tags: docker

    - role: dev
      tags: dev

- hosts: homeserver
  gather_facts: true
  become: true

  roles:
    - role: docker
      tags: docker
    
    - role: nas
      tags: nas