- name: mergerfs | configure | set cache disk facts
  ansible.builtin.set_fact:
    cache_disks: "{{ cache_disks | default([]) }}"
    cache_disks_only: "{{ cache_disks | default([]) | select('match', '^/dev/') | list }}"
    cache_paths_only: "{{ cache_disks | default([]) | reject('match', '^/dev/') | list }}"

- name: mergerfs | configure | set disk count facts
  ansible.builtin.set_fact:
    cache_disks_count: "{{ cache_disks_only | length }}"
    cache_sources_count: "{{ cache_disks | default([]) | length }}"
    cache_disks_exist: "{{ cache_disks | default([]) | length > 0 }}"
    data_disks_count: "{{ data_disks | length }}"

- name: mergerfs | configure | initialize data mounts list
  ansible.builtin.set_fact:
    data_mounts: []

- name: mergerfs | configure | generate data mounts list
  ansible.builtin.set_fact:
    data_mounts: "{{ data_mounts + [data_mount_path ~ '/data%02d' % (index + 1)] }}"
  loop: "{{ data_disks }}"
  loop_control:
    index_var: index
    label: "{{ data_mount_path }}/data{{ '%02d' % (index + 1) }}"