# Ngnix configuration
homelab_domain: "homelab"
homelab_server_ip: "{{ ansible_default_ipv4.address }}"

homelab_proxy_hosts:
  - name: glance
    domain: "glance.{{ homelab_domain }}"
    upstream: "http://glance:8080"

  - name: vaultwarden
    domain: "vaultwarden.{{ homelab_domain }}"
    upstream: "http://vaultwarden:80"

  - name: grafana
    domain: "grafana.{{ homelab_domain }}"
    upstream: "http://grafana:3000"

  - name: scrutiny
    domain: "scrutiny.{{ homelab_domain }}"
    upstream: "http://scrutiny:8080"
  
  - name: prometheus
    domain: "prometheus.{{ homelab_domain }}"
    upstream: "http://prometheus:9090"

  - name: adguard
    domain: "adguard.{{ homelab_domain }}"
    upstream: "http://adguard:3000"


# Vaultwarden configuration
vaultwarden_signups_allowed: "true"
vaultwarden_invitations_allowed: "false"
vaultwarden_websocket_enabled: "true"
vaultwarden_domain: "http://{{ ansible_host }}:{{ Vaultwarden }}"

vaultwarden_admin_token: "{{ lookup('password', 'credentials/vaultwarden_admin_token length=64 chars=ascii_letters,digits') }}"

# Adguard configuration
adguard_domain: "adguard.{{ homelab_domain }}"
adguard_admin_user: admin
adguard_admin_password: >-
  {{ lookup('password',
     'credentials/adguard_admin_password length=32 chars=ascii_letters,digits') }}