# Ngnix configuration
homelab_base_domain: "rothsrv.com"
homelab_domain: "home.rothsrv.com"
homelab_certificate_name: "home.rothsrv.com"

homelab_acme_email: "roth1.sandro@gmail.com"

cloudflare_dns_api_token: >-
  {{ lookup(
      'ansible.builtin.file',
      playbook_dir ~ '/credentials/nginx_token'
    ) | trim }}

homelab_server_ip: "{{ ansible_facts['default_ipv4']['address'] }}"

homelab_proxy_hosts:
  - name: glance
    domain: "glance.{{ homelab_domain }}"
    upstream: "http://glance:8080"

  - name: vaultwarden
    domain: "vaultwarden.{{ homelab_domain }}"
    upstream: "http://vaultwarden:80"

  - name: grafana
    domain: "grafana.{{ homelab_domain }}"
    upstream: "http://grafana:3000"

  - name: scrutiny
    domain: "scrutiny.{{ homelab_domain }}"
    upstream: "http://scrutiny:8080"
  
  - name: prometheus
    domain: "prometheus.{{ homelab_domain }}"
    upstream: "http://prometheus:9090"

  - name: filebrowser
    domain: 'filebrowser.{{ homelab_domain }}'
    upstream: 'http://filebrowser:80'

  - name: adguard
    domain: "adguard.{{ homelab_domain }}"
    upstream: "http://adguard:3000"

  - name: portainer
    domain: "portainer.{{ homelab_domain }}"
    upstream: "http://portainer:9000"

  - name: jellyfin
    domain: 'jellyfin.{{ homelab_domain }}'
    upstream: 'http://jellyfin:8096'
    allow_restricted_clients: true

  # - name: seerr
  #   domain: "seerr.{{ homelab_domain }}"
  #   upstream: "http://seerr:5055"
  #   allow_restricted_clients: true

  - name: sabnzbd
    domain: "sabnzbd.{{ homelab_domain }}"
    upstream: "http://sabnzbd:8080"

  - name: prowlarr
    domain: "prowlarr.{{ homelab_domain }}"
    upstream: "http://prowlarr:9696"


# Vaultwarden configuration
vaultwarden_signups_allowed: "true"
vaultwarden_invitations_allowed: "false"
vaultwarden_websocket_enabled: "true"
vaultwarden_domain: >-
  {{
    'https://vaultwarden.' ~ homelab_domain
    if homelab_services.core.nginx_proxy_manager | default(false)
    else 'http://' ~ ansible_host ~ ':' ~ (Vaultwarden | string)
  }}

vaultwarden_admin_token: "{{ lookup('password', 'credentials/vaultwarden_admin_token length=64 chars=ascii_letters,digits') }}"

# Adguard configuration
adguard_domain: "adguard.{{ homelab_domain }}"
adguard_admin_user: admin
adguard_admin_password: >-
  {{ lookup('password',
     'credentials/adguard_admin_password length=32 chars=ascii_letters,digits') }}

adguard_upstream_dns:
  - https://dns.quad9.net/dns-query
  - https://cloudflare-dns.com/dns-query

adguard_dns_rewrites:
  - domain: "*.{{ homelab_domain }}"
    answer: "{{ homelab_server_ip }}"

# Jellyfin configuration
jellyfin_admin_user: admin
jellyfin_admin_password: "{{ lookup('password', 'credentials/jellyfin_admin_password length=32 chars=ascii_letters,digits') }}"
jellyfin_server_name: "RothFlix"
jellyfin_ui_culture: "de-CH"
jellyfin_metadata_language: "de"
jellyfin_metadata_country: "CH"
jellyfin_enable_remote_access: false
jellyfin_enable_automatic_port_mapping: false

jellyfin_libraries:
  - name: Movies
    path: /media/movies
    collection_type: movies

  - name: TV Shows
    path: /media/tv
    collection_type: tvshows