# -------------------------------------------------
# Core user mapping
# -------------------------------------------------
nas_user: "{{ main_usr }}"
nas_group: "{{ usr_group }}"
nas_admin_group: "{{ admin_group }}"
nas_home: "{{ usr_home }}"
nas_shell: "{{ main_shell }}"

# -------------------------------------------------
# NAS feature toggles
# -------------------------------------------------
configure_samba: true
configure_snapraid: true
configure_mergerfs: true
configure_cache_mover: true
configure_scrutiny: true
configure_hdidle: false # problematic on btrfs partition!
install_rclone: true

# -------------------------------------------------
# Generic
# -------------------------------------------------
media_admin_group: media-admin
media_read_group: media-read
upload_group: upload-users

# -------------------------------------------------
# Mount paths
# -------------------------------------------------
media_cached: /mnt/media
media_noncached: /mnt/media
media_cold: /mnt/media-cold
data_mount_path: /mnt/data-disks
parity_mount_path: /mnt/parity-disks
cache_mount_path: /mnt/cache-disks
cache_pool: /mnt/cache-pool

# -------------------------------------------------
# Directories inside the media pool
# -------------------------------------------------
data_directories:
  - movies
  - tv
  - music
  - podcasts
  - fotos
  - documents

upload_root_directory: uploads
upload_users:
  - kesslers

# -------------------------------------------------
# Users and groups for NAS access
# -------------------------------------------------
users:
  - name: "{{ nas_user }}"
    groups:
      - "{{ media_admin_group }}"
      - "{{ media_read_group }}"
      - "{{ upload_group }}"
      - "{{ nas_admin_group }}"

  - name: jellyfin
    groups:
      - "{{ media_read_group }}"
    create_home: false
    shell: /sbin/nologin

  - name: media
    groups:
      - "{{ media_admin_group }}"
    create_home: false
    shell: /sbin/nologin

  - name: kesslers
    groups:
      - "{{ upload_group }}"
      - "{{ media_read_group }}"
    create_home: false
    shell: /sbin/nologin