- name: validate_fail2ban
  ansible.builtin.command: fail2ban-client -t
  changed_when: false

- name: restart_fail2ban
  block:
    - name: Stop fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: stopped

    - name: Remove stale fail2ban runtime files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/run/fail2ban/fail2ban.sock
        - /var/run/fail2ban/fail2ban.pid
        - /run/fail2ban/fail2ban.sock
        - /run/fail2ban/fail2ban.pid

    - name: Start fail2ban
      ansible.builtin.systemd:
        name: fail2ban
        state: started
        daemon_reload: true

- name: Reload sysctl
  listen: reload_sysctl
  ansible.builtin.command:
    cmd: /usr/sbin/sysctl --system
  changed_when: false

- name: Restart Node Exporter
  listen: restart_node_exporter
  become: true
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    state: restarted

- name: update_tmux_plugin_perms
  become: true #change permissions as root to ensure all files are owned by the main user
  ansible.builtin.file:
    path: "{{ usr_home }}/.tmux/plugins"
    owner: "{{ main_usr }}"
    group: "{{ main_usr }}"
    recurse: true

- name: update_vim_bundle_perms
  become: true #change permissions as root to ensure all files are owned by the main user
  ansible.builtin.file:
    path: "{{ usr_home }}/.vim/bundle"
    owner: "{{ main_usr }}"
    group: "{{ main_usr }}"
    recurse: true

- name: validate_fail2ban
  ansible.builtin.command: fail2ban-client -t
  changed_when: false
  listen: validate_fail2ban

- name: restart_fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true
  listen: restart_fail2ban