- include_vars: "ports.yml"
  tags: always

- name: homelab | dashboard
  block:

    - name: homelab_stack | dashboard | create docker network
      community.docker.docker_network:
        name: "{{ docker_network_name }}"
        state: present

    - import_tasks: "core/main.yml"
      tags: homelab_core

  when: ansible_facts.os_family == "Debian"
  become: true