- include_vars: "ports.yml"
  tags: always

- name: homelab | dashboard
  block:
    - import_tasks: "core/main.yml"
      tags: homelab_core

  when: ansible_facts.os_family == "Debian"
  become: true