- name: homelab_stack | filebrowser | Get required groups
  ansible.builtin.getent:
    database: group
    key: "{{ item }}"
  loop:
    - "{{ media_admin_group }}"
    - "{{ media_read_group }}"
    - "{{ upload_group }}"

- name: homelab_stack | filebrowser | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0755"
  loop:
    - "{{ homelab_config_dir }}/filebrowser"
    - "{{ homelab_compose_dir }}/filebrowser"

- name: homelab_stack | filebrowser | Create database file
  ansible.builtin.file:
    path: "{{ homelab_config_dir }}/filebrowser/database.db"
    state: touch
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0640"

- name: homelab_stack | filebrowser | Deploy settings file
  ansible.builtin.copy:
    dest: "{{ homelab_config_dir }}/filebrowser/settings.json"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0640"
    content: |
      {
        "port": 80,
        "baseURL": "",
        "address": "",
        "log": "stdout",
        "database": "/database.db",
        "root": "/srv"
      }

- name: homelab_stack | filebrowser | Get nas user UID
  ansible.builtin.command:
    cmd: "id -u {{ nas_user }}"
  register: filebrowser_uid_cmd
  changed_when: false

- name: homelab_stack | filebrowser | Get nas user GID
  ansible.builtin.command:
    cmd: "id -g {{ nas_user }}"
  register: filebrowser_gid_cmd
  changed_when: false

- name: homelab_stack | filebrowser | Get media admin group
  ansible.builtin.command:
    cmd: "getent group {{ media_admin_group }}"
  register: filebrowser_media_admin_group_cmd
  changed_when: false

- name: homelab_stack | filebrowser | Get upload group
  ansible.builtin.command:
    cmd: "getent group {{ upload_group }}"
  register: filebrowser_upload_group_cmd
  changed_when: false

- name: homelab_stack | filebrowser | Set group GID facts
  ansible.builtin.set_fact:
    filebrowser_media_admin_gid: "{{ filebrowser_media_admin_group_cmd.stdout.split(':')[2] }}"
    filebrowser_upload_gid: "{{ filebrowser_upload_group_cmd.stdout.split(':')[2] }}"

- name: homelab_stack | filebrowser | Deploy compose file
  ansible.builtin.template:
    src: filebrowser/docker-compose.yml.j2
    dest: "{{ homelab_compose_dir }}/filebrowser/docker-compose.yml"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0644"

- name: homelab_stack | filebrowser | Stop container before database management
  community.docker.docker_container:
    name: filebrowser
    state: stopped
  failed_when: false

- name: homelab_stack | filebrowser | Init database
  ansible.builtin.command:
    cmd: >
      docker run --rm
      -v {{ homelab_config_dir }}/filebrowser/database.db:/database.db
      filebrowser/filebrowser:latest
      --config /tmp/no-config.json
      -d /database.db config init
  register: filebrowser_config_init
  changed_when: filebrowser_config_init.rc == 0
  failed_when:
    - filebrowser_config_init.rc != 0
    - "'already exists' not in filebrowser_config_init.stderr"

- name: homelab_stack | filebrowser | Ensure upload folders exist
  ansible.builtin.file:
    path: "{{ media_cached }}/uploads/{{ item.name }}"
    state: directory
    owner: "{{ item.name }}"
    group: "{{ media_admin_group }}"
    mode: "0770"
  loop: "{{ samba_users }}"
  when: item.name != nas_user

- name: homelab_stack | filebrowser | Create users from samba users
  ansible.builtin.command:
    cmd: >
      docker run --rm
      -v {{ homelab_config_dir }}/filebrowser/database.db:/database.db
      filebrowser/filebrowser:latest
      --config /tmp/no-config.json
      -d /database.db users add
      {{ item.name }}
      {{ lookup(
        'password',
        'credentials/filebrowser_' ~ item.name ~ '_password length=32 chars=ascii_letters,digits'
      ) }}
      --scope {{
        '/media'
        if item.name == nas_user
        else '/media/uploads/' ~ item.name
      }}
  loop: "{{ samba_users }}"
  register: filebrowser_create_users
  changed_when: filebrowser_create_users.rc == 0
  failed_when:
    - filebrowser_create_users.rc != 0
    - "'already exists' not in filebrowser_create_users.stderr"
    - "'already exists' not in filebrowser_create_users.stdout"
  no_log: true

- name: homelab_stack | filebrowser | Update users from samba users
  ansible.builtin.command:
    cmd: >
      docker run --rm
      -v {{ homelab_config_dir }}/filebrowser/database.db:/database.db
      filebrowser/filebrowser:latest
      --config /tmp/no-config.json
      -d /database.db users update
      {{ item.name }}
      --password {{
        lookup(
          'password',
          'credentials/filebrowser_' ~ item.name ~ '_password length=32 chars=ascii_letters,digits'
        )
      }}
      --scope {{
        '/media'
        if item.name == nas_user
        else '/media/uploads/' ~ item.name
      }}
  loop: "{{ samba_users }}"
  changed_when: false
  no_log: true

- name: homelab_stack | filebrowser | Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ homelab_compose_dir }}/filebrowser"
    pull: always
    state: present