- name: homelab_stack | core | Create glance config directory
  ansible.builtin.file:
    path: "{{ homelab_config_dir }}/glance"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0755"

- name: homelab_stack | core | Create Glance assets directory
  ansible.builtin.file:
    path: "{{ homelab_config_dir }}/glance/assets"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0755"

- name: homelab_stack | core | Create Glance compose directory
  ansible.builtin.file:
    path: "{{ homelab_compose_dir }}/glance"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0755"

- name: homelab_stack | core | Deploy Glance configuration
  ansible.builtin.template:
    src: glance.yml.j2
    dest: "{{ homelab_config_dir }}/glance/glance.yml"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0644"

- name: homelab_stack | core | Deploy Glance compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ homelab_compose_dir }}/glance/docker-compose.yml"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0644"

- name: homelab_stack | core | Start Glance stack
  community.docker.docker_compose_v2:
    project_src: "{{ homelab_compose_dir }}/glance"
    pull: always
    state: present