- name: homelab_stack | core | ufw
  import_tasks: 'ufw.yml'
  when: homelab_services.core.ufw | default(false)

- name: homelab_stack | core | Install nginx
  import_tasks: 'nginx.yml'
  when: homelab_services.core.nginx_proxy_manager | default(false)

- name: homelab_stack | core | Install Vaultwarden
  import_tasks: 'vaultwarden.yml'
  when: homelab_services.core.vaultwarden | default(false)

- name: homelab_stack | core | Install glance
  import_tasks: 'glance.yml'
  when: homelab_services.core.glance | default(false)