- name: homelab_stack | nginx | Configure trusted certificates
  ansible.builtin.import_tasks: nginx_certificates.yml

- name: homelab_stack | nginx | Create server directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0755"
  loop:
    - "{{ homelab_config_dir }}/nginx/conf.d"
    - "{{ homelab_compose_dir }}/nginx"

- name: homelab_stack | nginx | Deploy nginx config
  ansible.builtin.template:
    src: nginx/default.conf.j2
    dest: "{{ homelab_config_dir }}/nginx/conf.d/default.conf"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0644"
  notify: Restart Nginx

- name: homelab_stack | nginx | Deploy compose file
  ansible.builtin.template:
    src: nginx/docker-compose.yml.j2
    dest: "{{ homelab_compose_dir }}/nginx/docker-compose.yml"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0644"

- name: homelab_stack | nginx | Allow HTTP internally
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: homelab_stack | nginx | Allow HTTPS internally
  community.general.ufw:
    rule: allow
    port: "443"
    proto: tcp

- name: homelab_stack | nginx | Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ homelab_compose_dir }}/nginx"
    pull: always
    state: present