- name: homelab_stack | vaultwarden | Create data directory
  ansible.builtin.file:
    path: "{{ homelab_config_dir }}/vaultwarden/data"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0750"

- name: homelab_stack | vaultwarden | Create compose directory
  ansible.builtin.file:
    path: "{{ homelab_compose_dir }}/vaultwarden"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0755"

- name: homelab_stack | vaultwarden | Deploy compose file
  ansible.builtin.template:
    src: vaultwarden/docker-compose.yml.j2
    dest: "{{ homelab_compose_dir }}/vaultwarden/docker-compose.yml"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0644"

- name: homelab_stack | vaultwarden | Allow port
  community.general.ufw:
    rule: allow
    port: "{{ Vaultwarden }}"
    proto: tcp

- name: homelab_stack | vaultwarden | Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ homelab_compose_dir }}/vaultwarden"
    pull: always
    state: present