locale_packages: [locales]
timesyncd_package: systemd-timesyncd
cron_package: cron
utilities_packages:
  - dnsutils    # collection of utilities for querying DNS servers - useful for troubleshooting and network diagnostics
  - iotop       # display I/O usage information for processes
  - lsof        # list open files - shows which processes currently have files open
  - mosh        # mobile shell - allows you to connect to a remote machine over SSH
  - ncdu        # Ncurses Disk Usage - a disk usage analyzer for terminal
  - neofetch    # system information tool - displays system information in a visually appealing way
  - nmap        # network exploration tool and security scanner - useful for discovering hosts and services on a network
  - ranger      # terminal file manager - provides a text-based interface for navigating and managing files
  - rsync       # remote synchronization tool - useful for backups and file transfers
  - sshfs       # SSH Filesystem - allows you to mount a remote filesystem over SSH
  - tmux        # terminal multiplexer - allows you to run multiple terminal sessions within a single window
  - traceroute  # network diagnostic tool - shows the route packets take to reach a destination
  - zsh         # Z Shell - an alternative to the default bash shell with additional features and customization options
