homelab_base_dir: /opt/docker
homelab_config_dir: "{{ homelab_base_dir }}/config"
homelab_compose_dir: "{{ homelab_base_dir }}/compose"

docker_network_name: homelab_stack

glance_services:
  core:
    - name: Portainer
      icon: si:portainer
      port: "{{ Portainer }}"

    - name: Vaultwarden
      icon: si:vaultwarden
      port: "{{ Vaultwarden }}"

    - name: File Browser
      icon: si:filebrowser
      port: "{{ FileBrowser }}"

  media:
    - name: Jellyfin
      icon: si:jellyfin
      port: "{{ Jellyfin }}"

    - name: Seerr
      icon: si:overseerr
      port: "{{ Seerr }}"

    - name: Sonarr
      icon: si:sonarr
      port: "{{ Sonarr }}"

    - name: Radarr
      icon: si:radarr
      port: "{{ Radarr }}"

    - name: Prowlarr
      icon: si:prowlarr
      port: "{{ Prowlarr }}"

    - name: qBittorrent
      icon: si:qbittorrent
      port: "{{ qBittorrentViaGluetun }}"

  monitoring:
    - name: Grafana
      icon: si:grafana
      port: "{{ Grafana }}"

    - name: Prometheus
      icon: si:prometheus
      port: "{{ Prometheus }}"

    - name: Scrutiny
      icon: si:smartthings
      port: 8081