homelab_base_dir: /opt/docker
homelab_config_dir: "{{ homelab_base_dir }}/config"
homelab_compose_dir: "{{ homelab_base_dir }}/compose"

docker_network_name: homelab_stack

glance_bookmarks:
  - group: Core
    links:
      - title: Portainer
        port: "{{ Portainer }}"
      - title: Vaultwarden
        port: "{{ Vaultwarden }}"
      - title: File Browser
        port: "{{ FileBrowser }}"

  - group: Media
    links:
      - title: Jellyfin
        port: "{{ Jellyfin }}"
      - title: Seerr
        port: "{{ Seerr }}"
      - title: Sonarr
        port: "{{ Sonarr }}"
      - title: Radarr
        port: "{{ Radarr }}"
      - title: Prowlarr
        port: "{{ Prowlarr }}"
      - title: qBittorrent
        port: "{{ qBittorrentViaGluetun }}"

  - group: Monitoring
    links:
      - title: Grafana
        port: "{{ Grafana }}"
      - title: Prometheus
        port: "{{ Prometheus }}"
      - title: Scrutiny
        port: 8081