- name: homelab_stack | jellyfin | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ nas_user }}"
    group: "{{ media_read_group }}"
    mode: "0775"
  loop:
    - "{{ homelab_config_dir }}/jellyfin"
    - "{{ homelab_config_dir }}/jellyfin/config"
    - "{{ homelab_config_dir }}/jellyfin/cache"
    - "{{ homelab_compose_dir }}/jellyfin"

- name: homelab_stack | jellyfin | Deploy compose file
  ansible.builtin.template:
    src: jellyfin/docker-compose.yml.j2
    dest: "{{ homelab_compose_dir }}/jellyfin/docker-compose.yml"
    owner: "{{ nas_user }}"
    group: "{{ nas_group }}"
    mode: "0644"

- name: homelab_stack | jellyfin | Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ homelab_compose_dir }}/jellyfin"
    pull: always
    state: present