- name: homelab_stack | media | Load shared media service IDs
  ansible.builtin.include_tasks:
    file: common.yml
    apply:
      tags:
        - always
  tags:
    - always

- name: homelab_stack | media | Install Jellyfin
  import_tasks: 'jellyfin.yml'
  when: homelab_services.media.jellyfin | default(false)

- name: homelab_stack | media | Configure SABnzbd
  ansible.builtin.include_tasks: sabnzbd.yml
  when: homelab_services.media.sabnzbd | default(false)
  tags: 
    - sabnzbd
    - usenet

- name: homelab_stack | media | Configure Prowlarr
  ansible.builtin.include_tasks: prowlarr.yml
  when: homelab_services.media.prowlarr | default(false)
  tags:
    - prowlarr
    - usenet

- name: homelab_stack | media | Configure Radarr
  ansible.builtin.include_tasks: radarr.yml
  when: homelab_services.media.radarr | default(false)
  tags:
    - radarr
    - usenet

- name: homelab_stack | media | Configure Sonarr
  ansible.builtin.include_tasks: sonarr.yml
  when: homelab_services.media.sonarr | default(false)
  tags:
    - sonarr
    - usenet

- name: homelab_stack | media | Sync with recyclarr
  ansible.builtin.include_tasks:
    file: recyclarr.yml
    apply:
      tags:
        - recyclarr
        - recyclarr_sync
        - usenet
  when:
    - homelab_services.media.sonarr | default(false) | bool
    - homelab_services.media.radarr | default(false) | bool
  tags:
    - recyclarr
    - recyclarr_sync
    - usenet

- name: homelab_stack | media | Configure Seerr
  ansible.builtin.include_tasks:
    file: seerr.yml
    apply:
      tags:
        - seerr
        - usenet
  when: homelab_services.media.seerr | default(false) | bool
  tags:
    - seerr
    - usenet