- name: Recyclarr | create configuration directory
  ansible.builtin.file:
    path: "{{ homelab_config_dir }}/recyclarr"
    state: directory
    owner: "{{ main_usr }}"
    group: "{{ media_admin_group }}"
    mode: "0775"

- name: Recyclarr | create compose directory
  ansible.builtin.file:
    path: "{{ homelab_compose_dir }}/recyclarr"
    state: directory
    owner: "{{ main_usr }}"
    group: "{{ media_admin_group }}"
    mode: "0775"

- name: Recyclarr | deploy compose file
  ansible.builtin.template:
    src: recyclarr/docker-compose.yml.j2
    dest: "{{ homelab_compose_dir }}/recyclarr/docker-compose.yml"
    owner: "{{ main_usr }}"
    group: "{{ media_admin_group }}"
    mode: "0644"

- name: Recyclarr | deploy configuration
  ansible.builtin.copy:
    dest: "{{ homelab_config_dir }}/recyclarr/recyclarr.yml"
    owner: "{{ main_usr }}"
    group: "{{ media_admin_group }}"
    mode: "0600"
    content: |
      radarr:
        radarr:
          base_url: http://radarr:7878
          api_key: "{{ radarr_api_key }}"

          quality_definition:
            type: movie

      sonarr:
        sonarr:
          base_url: http://sonarr:8989
          api_key: "{{ sonarr_api_key }}"

          quality_definition:
            type: series

- name: Recyclarr | synchronize Radarr and Sonarr
  community.docker.docker_compose_v2_run:
    project_src: "{{ homelab_compose_dir }}/recyclarr"
    service: recyclarr
    command: sync
    remove_orphans: true
  register: recyclarr_sync
  changed_when: "'No changes' not in recyclarr_sync.stdout"