---
# Core user mapping
nas_user: "{{ main_usr }}"
nas_group: "{{ usr_group }}"
nas_admin_group: "{{ admin_group }}"
nas_home: "{{ usr_home }}"
nas_shell: "{{ main_shell }}"

# NAS feature toggles
configure_samba: true
configure_snapraid: true
configure_mergerfs: true
configure_cache_mover: true
configure_scrutiny: true
configure_hdidle: false # problematic on btrfs partition!
install_rclone: true

# Generic
media_admin_group: media-admin
media_read_group: media-read
upload_group: upload-users

# Mount paths
media_cached: /mnt/media
media_noncached: /mnt/media
media_cold: /mnt/media-cold
data_mount_path: /mnt/data-disks
parity_mount_path: /mnt/parity-disks
cache_mount_path: /mnt/cache-disks
cache_pool: /mnt/cache-pool

# MergerFS
cache_pool_policy: epmfs
pool_policy: epmfs
configure_mergerfs_cache_minfreespace: 50G
configure_mergerfs_minfreespace: 100G
mergerfs_dist: "{{ ansible_facts.distribution | lower }}-{{ ansible_facts.distribution_release }}"
mergerfs_arch_map:
  x86_64: amd64
  i386: i386
  aarch64: arm64
  armv7l: armhf
mergerfs_arch: "{{ mergerfs_arch_map[ansible_facts.userspace_architecture | default(ansible_facts.architecture)] }}"
mergerfs_pkg_prefix: mergerfs_
mergerfs_pkg_suffix: .{{ mergerfs_dist }}_{{ mergerfs_arch }}.deb
configure_mergerfs_minfreespace: 100G
configure_mergerfs_cache_minfreespace: 50G
pool_policy: epmfs

# SnapRAID
configure_snapraid_snapraid_deletethreshold: 150
split_parity_files: 3
split_parity_migrate: true
snapraid_excludes: []

content_files:
  - /var/snapraid/snapraid.content
  - /mnt/parity-disks/parity01/snapraid/snapraid.content
  - /mnt/cache-disks/cache01/snapraid/cache/snapraid.content

dir_snapraid_btfs_runner: /var/snapraid-btrfs-runner

# Directories inside the media pool
data_directories:
  - movies
  - tv
  - music
  - podcasts
  - fotos
  - documents

upload_root_directory: uploads

upload_users:
  - kesslers

# Users and groups for NAS access
users:
  - name: "{{ nas_user }}"
    groups:
      - "{{ media_admin_group }}"
      - "{{ media_read_group }}"
      - "{{ upload_group }}"
      - "{{ nas_admin_group }}"

  - name: jellyfin
    groups:
      - "{{ media_read_group }}"
    create_home: false
    shell: /sbin/nologin

  - name: media
    groups:
      - "{{ media_admin_group }}"
    create_home: false
    shell: /sbin/nologin

  - name: kesslers
    groups:
      - "{{ upload_group }}"
      - "{{ media_read_group }}"

# Samba
samba_users:
  - name: "{{ nas_user }}"
    password: "{{ lookup('password', 'credentials/samba_{{ nas_user }}_password length=32 chars=ascii_letters,digits') }}"

  - name: kesslers
    password: "{{ lookup('password', 'credentials/samba_kesslers_password length=32 chars=ascii_letters,digits') }}"

samba_global_config_extras: |
  socket options = TCP_NODELAY IPTOS_LOWDELAY SO_RCVBUF=262144 SO_SNDBUF=262144
  read raw = yes
  write raw = yes
  max xmit = 65536
  dead time = 15
  getwd cache = yes
  strict allocate = yes
  allocation roundup size = 4096
  aio read size = 65536
  aio write size = 65536
  use sendfile = yes
  server multi channel support = yes

samba_shares:
  - name: movies
    path: "{{ media_cached }}/movies"
    guest_ok: false
    writable: false
    read_only: true
    valid_users: "@{{ media_read_group }}, {{ nas_user }}"
    force_group: "{{ media_read_group }}"

  - name: tv
    path: "{{ media_cached }}/tv"
    guets_ok: false
    writable: false
    read_only: true
    valid_users: "@{{ media_read_group }}, {{ nas_user }}"
    force_group: "{{ media_read_group }}"

  - name: uploads
    path: "{{ media_cached }}/{{ upload_root_directory }}/%U"
    guest_ok: false
    writable: true
    read_only: false
    valid_users: "@{{ upload_group }}, {{ nas_user }}"
    force_group: "{{ upload_group }}"
    create_mode: "0770"
    directory_mode: "0770"
    force_create_mode: "0770"
    force_directory_mode: "0770"

# Disk setup
wipe_and_setup: true

data_disks:
  - /dev/disk/by-id/ata-WDC_WD80EFZZ-68BTXN0_WD-CA2A8SSK  #8TB
  - /dev/disk/by-id/ata-WDC_WD80EFZZ-68BTXN0_WD-CA2AY9ZK  #8TB
  - /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QKSZBYB    #12TB

cache_disks:
  - /opt/mergerfs-cache                                   #create folder on the OS-NvME

parity_disks:
  - device: /dev/disk/by-id/ata-WDC_WD120EFBX-68B0EN0_5QKRGGZB    #12TB
    mode: dedicated
    level: 1

partition_path: >-
  {{
    device + '-part' + partition if '-part' in device
    else device + 'p' + partition if device.startswith('/dev/nvme')
    else device + partition if device.startswith('/dev/sd')
    else null | mandatory('Only /dev/nvme* and /dev/sd* device paths are supported')
  }}

manage_disks_nas_btrfs_mount_opts: subvol=data,nofail
manage_disks_nas_ext4_mount_opts: defaults,nofail  


# Cache mover
cache_mover_autoupdate: true
cache_mover_update_branch: main
cache_mover_dir: /opt/mergerfs-cache-mover
cache_mover_log_path: /var/log/cache-mover.log
cache_mover_threshold_percentage: 70
cache_mover_target_percentage: 30
cache_mover_max_workers: 8
cache_mover_max_log_size_mb: 100
cache_mover_log_backup_count: 5
cache_mover_excluded_dirs: []
on_calendar_schedule: "*-*-* 03:00:00"

cache_mover_notif_enabled: false
cache_mover_notif_urls: []
cache_mover_notif_threshold: true

# Scrutiny
scrutiny_mode: omnibus
scrutiny_master_url: "http://scrutiny-master:8080"
scrutiny_webui_port: 8080

scrutiny_discord_enabled: false
scrutiny_telegram_enabled: false
scrutiny_pushover_enabled: false
scrutiny_slack_enabled: false
scrutiny_gotify_enabled: false
scrutiny_ntfy_enabled: false
scrutiny_pushbullet_enabled: false