scrutiny_image: >-
  {{
    'ghcr.io/starosdev/scrutiny:latest-collector'
    if scrutiny_mode == 'collector'
    else 'ghcr.io/starosdev/scrutiny:latest-omnibus'
  }}

scrutiny_user: "{{ nas_user }}"
scrutiny_group: "{{ media_admin_group }}"

scrutiny_base_path: /opt/docker/scrutiny
scrutiny_config_path: "{{ scrutiny_base_path }}/config"
scrutiny_data_path: "{{ scrutiny_base_path }}/data"
scrutiny_influxdb_path: "{{ scrutiny_base_path }}/influxdb2"
scrutiny_config_file: "{{ scrutiny_config_path }}/scrutiny.yaml"

scrutiny_ports:
  - "{{ scrutiny_webui_port }}:8080"
  - "8086:8086"

scrutiny_volumes:
  - "{{ scrutiny_config_path }}:/opt/scrutiny/config"
  - "{{ scrutiny_data_path }}:/opt/scrutiny/data"
  - "{{ scrutiny_influxdb_path }}:/opt/scrutiny/influxdb"
  - "{{ scrutiny_config_file }}:/opt/scrutiny/config/scrutiny.yaml"
  - "/run/udev:/run/udev:ro"
  - "/dev:/dev:ro"

scrutiny_devices:
  - label: DISK01
    device: "{{ data_disks[1] }}"
    type: sat

  - label: DISK02
    device: "{{ data_disks[0] }}"
    type: sat

  - label: DISK03_PARITY01
    device: "{{ parity_disks[0].device }}"
    type: sat

  - label: DISK04
    device: "{{ data_disks[2] }}"
    type: sat

  - label: NVME01_OS_CACHE
    device: /dev/nvme0
    type: nvme