- name: docker | cadvisor | Run container
  tags: cadvisor
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart_policy: unless-stopped
    ports:
      - "{{ cadvisor_listen_address | default('127.0.0.1:8080') }}:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true