- include_vars: "{{ ansible_facts.os_family }}.yml"
  when: ansible_facts.os_family in ['Debian']

- name: Install Debian settings
  include_tasks: setup-Debian.yml
  changed_when: false
  when: ansible_facts.os_family in ['Debian']

- name: Install Docker packages (with downgrade option)
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: "{{ docker_packages_state }}"
    allow_downgrade: true
    update_cache: true
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"
  when: ansible_facts.os_family in ['Debian']

- name: Install docker-compose-plugin (with downgrade option)
  ansible.builtin.apt:
    name: "{{ docker_compose_package }}"
    state: "{{ docker_compose_package_state }}"
    allow_downgrade: true
    update_cache: true
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"
  when: 
    - docker_install_compose_plugin | bool 
    - ansible_facts.os_family in ['Debian']

- name: Ensure etc/docker directory exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: docker_daemon_options.keys() | length > 0

- name: Configure Docker daemon options
  ansible.builtin.copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  when: docker_daemon_options.keys() | length > 0
  notify: restart docker

- name: Replace Docker service ExecStart command if configured.
  when: docker_service_start_command != ""
  notify: restart docker
  block:
    - name: Get Docker service status
      ansible.builtin.systemd_service:
        name: docker
      register: docker_service_status

    - name: Patch docker.service
      ansible.builtin.replace:
        path: "{{ docker_service_status.status['FragmentPath'] }}"
        regexp: "^ExecStart=.*$"
        replace: "ExecStart={{ docker_service_start_command }}"
      register: docker_service_patch

    - name: Reload systemd services
      service:
        daemon_reload: true
      when: docker_service_patch is changed

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

