- name: Install Docker packages (with downgrade option)
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: "{{ docker_packages_state }}"
    allow_downgrade: true
    update_cache: true
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"
  when: ansible_facts.os_family in ['Debian']

- name: Install docker-compose-plugin (with downgrade option)
  ansible.builtin.apt:
    name: "{{ docker_compose_package }}"
    state: "{{ docker_compose_package_state }}"
    allow_downgrade: true
    update_cache: true
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"
  when: 
    - docker_install_compose_plugin | bool 
    - ansible_facts.os_family in ['Debian']