---
branch: main

main_usr: sandro
admin_group: sudo
usr_group: sandro
main_shell: /bin/zsh
ansible_python_interpreter: /usr/bin/python3

# User
usr_home: /home/sandro

# paltform specific
microcode_amd_install: true
microcode_intel_install: false
swappiness_value: 10
install_fwupd: false
wireguard_enabled: true

# Audoupdate (Debian/Ubuntu)
security_autoupdate_enable: true
security_autoupdate_reboot: false
security_autoupdate_reboot_time: "02:00"
security_autoupdate_mail_to: "sandro.roth@hotmail.de"
security_autoupdate_mail_on_error: true
security_autoupdate_blacklist: [] # List of packages to exclude from automatic updates

# Visual host and docker level metrics
install_node_exporter: true # host metricts
node_exporter_listen_address: '127.0.0.1:9100'
install_cAdvisor: true # docker metrics
cadvisor_listen_address: "127.0.0.1:8080"

# Backup settings
backup_dir: /opt/backups
backup_script: /usr/local/bin/server-backup.sh

# microcode setup
amd_microcode_package: amd64-microcode
intel_microcode_package: intel-microcode