- include_vars: "{{ ansible_facts['distribution'] }}.yml"
  tags: always

- block:

  - name: system setup | timezone
    import_tasks: system_setup/timezone.yml

  - name: system setup | locale
    import_tasks: system_setup/locale.yml

  - name: system setup | hostname
    import_tasks: system_setup/hostname.yml

  - name: system setup | sysctl
    import_tasks: system_setup/sysctl.yml

  - name: software | apt | update cache
    ansible.builtin.apt:
      update_cache: true
      cache_valid_time: 7200

  - name: software | common packages
    import_tasks: software/common_packages.yml
  
  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']
  become: true