- include_vars: "{{ ansible_facts['distribution'] }}.yml"
  tags: always

- block:

  - name: system setup | timezone
  - include_tasks: system_setup/timezone.yml

  when: ansible_facts['distribution'] in ['Debian', 'Ubuntu']
  become: true