- include_vars: "{{ ansible_facts.os_family }}.yml"
  tags: always

- block:

  - import_tasks: system_setup/remove_users.yml
  - import_tasks: system_setup/disk_wipe.yml
  - include_role:
      name: stefangweichinger.ansible_rclone
    when: install_rclone
  - include_tasks: system_setup/installs.yml


  when: ansible_facts.os_family in ['Debian']
  become: true