- include_vars: "{{ ansible_facts.os_family }}.yml"
  tags: always

- name: nas | system_setup
  tags: nas_system, disks, mergerfs, snapraid, btrfs
  block:

    - import_tasks: system_setup/remove_users.yml
    - import_tasks: system_setup/disk_wipe.yml
    - include_role:
        name: stefangweichinger.ansible_rclone
      when: install_rclone
    - import_tasks: system_setup/installs.yml

  when: ansible_facts.os_family == "Debian"
  become: true

- name: nas | manage_disks
  tags: disks
  block:

    - import_tasks: manage_disks/prepare_disks.yml
    - import_tasks: manage_disks/configure_subvolumes.yml
    - import_tasks: manage_disks/configure_subvolume_mount.yml
    - import_tasks: manage_disks/configure_parity_cache.yml
    - import_tasks: manage_disks/configure_mount_perms.yml
    - import_tasks: manage_disks/cleanup_orphaned_mounts.yml

  when: ansible_facts.os_family == "Debian"
  become: true
  
- name: nas | mergerfs
  tags: mergerfs
  block:
    
    - import_tasks: mergerfs/configure.yml
    - import_tasks: mergerfs/media_cached.yml
      when: cache_disks_exist
    - import_tasks: mergerfs/media_cold.yml
      when: cache_disks_exist
    - import_tasks: mergerfs/media_noncached.yml
      when: not cache_disks_exist
    - import_tasks: mergerfs/upload.yml
    - import_tasks: mergerfs/create_data_directories.yml
    - import_tasks: mergerfs/configure_fuse.yml
    - import_tasks: mergerfs/configure_perms.yml
    - import_tasks: mergerfs/cleanup.yml

  when: ansible_facts.os_family == "Debian"
  become: true

- name: nas | snapraid
  tags: snapraid
  block:

    - include_vars: "snapraid.yml"
    - import_tasks: snapraid/install_snapper.yml
    - import_tasks: snapraid/install_snapraid-btrfs.yml
    - import_tasks: snapraid/check_parity_format.yml
    - import_tasks: snapraid/configure_snapraid.yml
    - import_tasks: snapraid/snapper_config.yml
    - import_tasks: snapraid/configure_snapraid-btrfs-runner.yml

  when: ansible_facts.os_family == "Debian"
  become: true

- name: nas | samba
  tags: samba
  block:
  
    - include_role: 
        name: vladgh.samba.server
  
  when: ansible_facts.os_family == "Debian"
  become: true

- name: nas | cache mover
  tags: cache_mover
  block:

    - import_tasks: cache_mover.yml

  when: ansible_facts.os_family == "Debian"
  become: true