- import_tasks: precondition.yml

- block:
    - import_tasks: install.yml
    - import_tasks: keys.yml
  when: 
    - wireguard_phase == 'keys'
    - wireguard_enabled | default(false) | bool
    - wireguard_has_server | bool
    - wireguard_has_client | bool

- block:
    - import_tasks: config.yml
  when: 
    - wireguard_phase == 'config'
    - wireguard_enabled | default(false) | bool
    - wireguard_has_server | bool
    - wireguard_has_client | bool