- name: system setup | locale | Ensure locale packages are installed
  tags: locale
  ansible.builtin.apt:
    name: "{{ locale_packages }}"
    state: present
    update_cache: true

- name: system setup | locale | Generate locale
  tags: locale
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ gen_locales}}"

- name: system setup | locale | Set system locale
  tags: locale
  ansible.builtin.copy:
    dest: /etc/default/locale
    owner: root
    group: root
    mode: '0644'
    content: |
      LANG={{ base_locale | default('en_US.UTF-8') }}
      LC_ALL={{ base_locale | default('en_US.UTF-8') }}