- name: system setup | logging | configure journald retention
  tags: logging
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?MaxRetentionSec="
    line: "MaxRetentionSec=5day"
    create: yes
  register: journald_config
  when: ansible_service_mgr == "systemd"

- name: system setup | logging | restart journald if config changed
  tags: logging
  service:
    name: systemd-journald
    state: restarted
  when:
    - ansible_service_mgr == "systemd"
    - journald_config.changed