- name: system setup | logging | ensure journald config directory exists
  tags: logging
  ansible.builtin.file:
    path: /etc/systemd/journald.conf.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: ansible_facts['service_mgr'] == "systemd"

- name: system setup | logging | deploy journald limits
  tags: logging
  ansible.builtin.template:
    src: journald.conf.j2
    dest: /etc/systemd/journald.conf.d/99-server-limits.conf
    owner: root
    group: root
    mode: "0644"
  register: journald_config
  when: ansible_facts['service_mgr'] == "systemd"

- name: system setup | logging | restart journald if config changed
  tags: logging
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
  when:
    - ansible_facts['service_mgr'] == "systemd"
    - journald_config.changed