- name: system_setup | sysctl | Apply sysctl settings
  tags: sysctl
  ansible.posix.sysctl:
    name: {{ item.key }}
    value: {{ item.value }}
    state: present
    reload: true
  loop: "{{ base_sysctl_settings }}"