- name: system_setup | sysctl | Ensure procps is installed
  tags: sysctl
  ansible.builtin.apt:
    name: procps
    state: present
    update_cache: true
    cache_valid_time: 7200

- name: system_setup | sysctl | Apply sysctl settings
  tags: sysctl
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    reload: false
  loop: "{{ base_sysctl_settings | dict2items }}"
  notify: reload_sysctl